apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: rails-app  # Matches Kamal’s default image name
      context: .
      docker:
        dockerfile: Dockerfile
    - image: web-frontend
      context: ./frontend
      docker:
        dockerfile: frontend/Dockerfile.frontend
manifests:
  rawYaml:
    - k8s/backend.yml
    - k8s/backend-service.yml
    - k8s/web-frontend.yml
    - k8s/web-frontend-service.yml
    - k8s/mysql.yml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: rails-service
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: web-frontend-service
    port: 4000
    localPort: 4000
  - resourceType: service
    resourceName: db
    port: 3306
    localPort: 3306  # Forward MySQL to localhost:3306