apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: web-frontend
      context: ./frontend
      docker:
        dockerfile: frontend/Dockerfile.frontend
      sync:
        manual:
          # Sync JS files that are updated at runtime, to the container without redeployment
          - src: 'app/**/*.js'
            dest: /app/app
          # Same for typescript files
          - src: 'lib/**/*.js'
            dest: /app/lib
          - src: 'reducers/**/*.js'
            dest: /app/reducers
          - src: 'sagas/**/*.js'
            dest: /app/sagas
          - src: 'selectors/**/*.js'
            dest: /app/selectors
          - src: 'containers/**/*.js'
            dest: /app/containers
    - image: rails-app  # Matches Kamal’s default image name
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # Sync Ruby files (models, controllers, etc.) to the container without redeployment
          - src: 'app/**/*.rb'
            dest: app  # Syncs to /rails/app
          - src: 'lib/**/*.rb'
            dest: lib  # Syncs to /rails/lib
          - src: 'db/**/*.rb'
            dest: ./db
manifests:
  rawYaml:
    - k8s/backend.yml
    - k8s/backend-service.yml
    - k8s/web-frontend.yml
    - k8s/web-frontend-service.yml
    - k8s/mysql.yml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: rails-service
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: web-frontend-service
    port: 4000
    localPort: 4000
  - resourceType: service
    resourceName: db
    port: 3306
    localPort: 3306  # Forward MySQL to localhost:3306