'use client';

import { Geist, Geist_Mono } from "next/font/google";
import { CacheProvider } from '@emotion/react';
import createCache from '@emotion/cache';
import { Provider } from 'react-redux';
import { store } from '@/lib/store';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Reward Manager",
//   description: "Manages Rewards - Generated by create next app",
// };

const cache = createCache({ key: 'mui', prepend: true });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CacheProvider value={cache}>
          <Provider store={store}>
            {children}
          </Provider>
        </CacheProvider>
      </body>
    </html>
  );
}