apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails
        image: rails-app
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "development"
        - name: DB_HOST
          value: "db"
